//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balu0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malha
    {
        public int ID_Ref { get; set; }
        public string Ref_Malha { get; set; }
        public Nullable<System.DateTime> Data_Registo { get; set; }
        public Nullable<System.DateTime> Data_Arquivo { get; set; }
        public string Ref_Malheiro { get; set; }
        public string Nome_Malha { get; set; }
        public Nullable<decimal> Largura { get; set; }
        public Nullable<int> Gramagem_Inicio { get; set; }
        public Nullable<int> Gramagem_Fim { get; set; }
        public Nullable<decimal> Gramagem_m2 { get; set; }
        public Nullable<decimal> Gramagem_mlinear { get; set; }
        public Nullable<int> ID_Unidade { get; set; }
        public Nullable<decimal> Valor_Unidade { get; set; }
        public Nullable<int> Pasta { get; set; }
        public Nullable<int> Cartaz { get; set; }
        public Nullable<decimal> Percentagem { get; set; }
        public Nullable<int> ID_Tingimento { get; set; }
        public Nullable<decimal> Preco_Malha_Cru { get; set; }
        public Nullable<decimal> Percas { get; set; }
        public Nullable<decimal> Preco_Final { get; set; }
        public string Obs { get; set; }
        public string Obs_temp { get; set; }
        public Nullable<int> ID_Fornecedor { get; set; }
        public string Obs_temp2 { get; set; }
        public string Malha_Composicao { get; set; }
        public Nullable<bool> Excluir { get; set; }
    }
}
