//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balu0._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaluEntities : DbContext
    {
        public BaluEntities()
            : base("name=BaluEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Malha> Malha { get; set; }
        public virtual DbSet<Preco_Malha> Preco_Malha { get; set; }
        public virtual DbSet<Programa> Programa { get; set; }
        public virtual DbSet<Programa_Cor> Programa_Cor { get; set; }
        public virtual DbSet<Programa_Cor_Info> Programa_Cor_Info { get; set; }
        public virtual DbSet<Programa_Cor_Info_Status> Programa_Cor_Info_Status { get; set; }
        public virtual DbSet<Programa_Malha> Programa_Malha { get; set; }
    }
}
