//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balu0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preco_Malha
    {
        public int Ref_Balu { get; set; }
        public int ID_PrecoPOS { get; set; }
        public int ID_Preco_Malha { get; set; }
        public Nullable<int> ID_Ref { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> Preco_Simulado { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> ID_Peso_Malha { get; set; }
        public Nullable<int> Peso_malha { get; set; }
        public Nullable<int> Comprimento { get; set; }
        public Nullable<int> Num_Pecas { get; set; }
        public Nullable<decimal> Valor_Peso_Peca { get; set; }
    }
}
