//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balu0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa_Malha
    {
        public int ID_Programa_Malha { get; set; }
        public int ID_Programa { get; set; }
        public string Num_Enc_Malha { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Obs { get; set; }
        public string Obs_Malha { get; set; }
        public string id_ref { get; set; }
        public Nullable<int> ID_Encomenda { get; set; }
    }
}
