//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balu0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa
    {
        public int ID_Programa { get; set; }
        public Nullable<System.DateTime> Data_Registo { get; set; }
        public string Num_Encomenda { get; set; }
        public string Ref_Cliente { get; set; }
        public string Colecao { get; set; }
        public Nullable<int> Ref_Balu { get; set; }
        public Nullable<System.DateTime> Semana_Embarque { get; set; }
        public string Modelo { get; set; }
        public Nullable<bool> Embarque { get; set; }
        public Nullable<System.DateTime> Data_Faturacao { get; set; }
        public Nullable<decimal> Valor_Faturacao { get; set; }
        public string Nummer { get; set; }
        public string PM { get; set; }
        public Nullable<bool> Comissao { get; set; }
        public Nullable<System.DateTime> Data_Comissao { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> Data_Aprovacao { get; set; }
        public Nullable<decimal> Preco_Peca { get; set; }
        public Nullable<int> Num_Semana { get; set; }
        public Nullable<int> Num_Pecas { get; set; }
        public Nullable<bool> Pronto_Embarcar { get; set; }
        public Nullable<bool> Excluir { get; set; }
        public string Cod_Artigo { get; set; }
        public Nullable<int> ImprimirLista { get; set; }
        public Programa()
        {
            this.ReturnDatePro = DateTime.Now;
            this.ReturnDateProDez = DateTime.Now.AddDays(+10);
        }

        public Nullable<System.DateTime> ReturnDatePro { get; set; }
        public Nullable<System.DateTime> ReturnDateProDez { get; set; }
    }
}
