//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balu0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa_Cor_Info
    {
        public int ID_Programa { get; set; }
        public int ID_Linha_Cor { get; set; }
        public int ID_Programa_Malha { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Fatura { get; set; }
        public Nullable<bool> Faturado { get; set; }
    }
}
